### ISSUE TITLE
Does not work with the following demo

### ISSUE THREAD

**Issue by wictorwilen** [guybedford/systemjs-webpack-plugin#1]
(Sorry about the weird issue name :-)

I tried out this plugin with a sample that I built using System.js and Webpack and stumbled upon a few errors.

The demo can be found at: https://github.com/wictorwilen/webpack-dynamic-modules/tree/multiplewidgets (the multiplewidgets branch is what you want to use)

If I use Webpack 2 and this plugin I first of all get an error due to that there are external modules, so it fails when trying to get rawRequest/resource and more. I changed that to:

```
var moduleObjs = modules.map(function (m) {
    if (m.constructor.name === 'NormalModule') {
      return {
        id: m.id,
        request: m.rawRequest,
        path: m.resource,
        relPath: m.resource.substr(0, path.length + 1) == path + sep ? m.resource.substr(path.length + 1) : m.resource,
        meta: m.meta
      };
    } else {
      return {
        id: m.id,
        request: "",
        path: "",
        relPath: "",
        meta: m.meta
      };
    }
  });
```

That change made it go through but the demo doesn't work and I get this error in the browser: `ReferenceError: publicESModules is not defined(`

I really want this plugin to work, and getting that demo to work. Keep up the good work and I'll contribute with tests as much as I can.

**Comment by guybedford** [comment]
Thanks for trying it out.

I've added https://github.com/guybedford/systemjs-webpack-plugin/commit/38f513c5f321de146101cc71fadd0ba5114a795c and https://github.com/guybedford/systemjs-webpack-plugin/commit/42a3b78b2d10caa9f3fc071d8f9aff9747d5070f for the externals and public modules issues respectively. Let me know if that helps for you here!

**Comment by wictorwilen** [comment]
Thanks, now I don't get any errors when running Webpack, but I don't understand how to do the configuration of the plugin so that it during runtime dynamically load my chunks

**Comment by guybedford** [comment]
@wictorwilen thanks for reporting back. It should be automatically configured to load the chunks as needed. For example if you run in the browser console - `System.import('lodash')` where say `lodash` is in an external chunk, it should then load that chunk.

**Comment by guybedford** [comment]
(the lodash example specifically applies through this filter line - https://github.com/guybedford/systemjs-webpack-plugin/blob/master/test/example-project/webpack.config.js#L10)

**Comment by wictorwilen** [comment]
The thing here is that I have the modules/chunks defined in the same Webpack config. That is I'm splitting up my project into multiple pieces. I made a very simple plugin that keeps all `system.import` calls intakt: you can find it here: https://github.com/wictorwilen/keepsystemjs.webpack.plugin

**Comment by guybedford** [comment]
I'm not sure I follow what the difference is. Perhaps you can clarify how the chunks aren't loading for you. Do you have multiple webpack projects that you need to tie the bundles config across them?

**Comment by wictorwilen** [comment]
Sure, I have one webpack config file, which outputs three files; one main and two additional. The main file uses system.import (before webpacking) to dynamically load the other files on demand. When using this plugin I did not get it to work, it said something about that it could not find the module. What I want is exactly what my plugin, above does, keep the system.import intact.

**Comment by guybedford** [comment]
@wictorwilen this case is completely supported, it just sounds like a configuration issue with ensuring the `System.import` name matches the public names in the registry. Make sure the publicModules keyname function is returning the same key name as used by the SystemJS import function.
